# Site settings
title: Anwarvic
description: "I write about research papers in these topics"
url: 'https://anwarvic.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Mohamed Anwar'
  pronouns: "(he/him/his)"
  email: mohamedanwarvic@gmail.com
  github:  anwarvic
  linkedin:  anwarvic
  stackoverflow:  5612363/anwarvic
  hackerrank: anwarvic
  leetcode: anwarvic


collections_dir: my_collections

collections:
  language-modeling:
    output: true
    permalink: /:collection/:path
  machine-translation:
    output: true
    permalink: /:collection/:path
  multilingual-nmts:
    output: true
    permalink: /:collection/:path
  word-embedding:
    output: true
    permalink: /:collection/:path



# defaults:
#   -
#     scope:
#       path: ''
#       type: 'posts'
#     values:
#         layout: 'post'

# Build settings
destination: _site
# paginate: 10
permalink: /:collection
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  mathjax: true
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

# plugins:
#   - jekyll-paginate
#   - jekyll-spaceship

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
