# Site settings
title: Anwarvic
description: "I write about research papers in these topics"
url: 'https://anwarvic.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

topics: ["Language Models", "Machine Translation", "Multilingual NMT",
         "Word Embeddings", "Speech Recognition"]

author:
  name: 'Mohamed Anwar'
  email: mohamedanwarvic@gmail.com
  github_username:  anwarvic
  linkedin_username:  anwarvic
  stackoverflow_username:  5612363/anwarvic

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
