# Site settings
title: Anwarvic
description: "I write about research papers in these topics"
url: 'https://anwarvic.github.io'
cover: images/space.jpg
baseurl: 'https://anwarvic.github.io/'
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'anwarvic'
# disable_landing_page: true

author:
  name: 'Mohamed Anwar'
  pronouns: "(he/him/his)"
  email: mohamedanwarvic@gmail.com
  github:  anwarvic
  linkedin:  anwarvic
  stackoverflow:  5612363/anwarvic
  hackerrank: anwarvic
  leetcode: anwarvic


collections_dir: my_collections

collections:
  language-modeling:
    output: true
    permalink: /:collection/:path
    title: "Language Modeling"
  machine-translation:
    output: true
    permalink: /:collection/:path
    title: "Machine Translation"
  multilingual-nmts:
    output: true
    permalink: /:collection/:path
    title: "Multilingual NMTs"
  word-embedding:
    output: true
    permalink: /:collection/:path
    title: "Word Embedding"
  speech-recognition:
    output: true
    permalink: /:collection/:path
    title: "Speech Recognition"

defaults:
  -
    scope:
      path: "my_collections/*" # all files inside my_collections
    values:
      layout: "post" #post.html

# Build settings
destination: _site
# paginate: 10
# permalink: /:collection
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  mathjax: true  #use mathjax to process math equations
  input: GFM # use Github Flavored Markdown
  hard_wrap: false # do not replace newlines by <br>

# plugins:
#   - jekyll-paginate
#   - jekyll-spaceship

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
